import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const workSans = localFont({
  src: [
    {
      path:"../../public/fonts/static/WorkSans-Regular.ttf",
      weight:"100 900",
      style:"normal",
    },
    {
      path:"../../public/fonts/static/WorkSans-Bold.ttf",
      weight:"100 900",
      style:"bold",
    },
    {
      path:"../../public/fonts/static/WorkSans-SemiBold.ttf",
      weight:"100 900",
      style:"semi-bold",
    },
  ],
  variable: "--font-work-sans"
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${workSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
